### ISSUE TITLE
Issue training with GPU on Linux

### ISSUE THREAD

**Issue by robertallenmartin** [apple/turicreate#3186]
Thank you for Turi Create. The style transfer API is really amazing. I am having trouble with training on a GPU with an AWS Ubuntu server. If anyone has any advice I would be very grateful.

Around October 2019 I was able to create an AWS Ubuntu server and train images on the GPU. It was blazing fast. I tried to repeat my set up this week May 2020, but now I have errors. I am sure versions of every dependency has updated or changed since I last built an environment using Linux to do the training or I am simply missing something new completely. The error I get is pasted at the end of this post.

Steps to reproduce the error are here...

1)
Choose an EC2 Amazon Machine Image (AMI)

- Deep Learning AMI (Ubuntu 18.04) Version 28.1 - ami-078a7f1dda72c0775

- MXNet-1.6.0, Tensorflow-2.1.0 & 1.15.2, PyTorch-1.4.0, Keras-2.2, & other frameworks, configured with Neuron, NVIDIA CUDA, cuDNN, NCCL, Intel MKL-DNN, Docker & NVIDIA-Docker. 

2)
Choose an Instance Type
- g3s.xlarge

3)
- During EC2 setup process - Set access to use only your IP address

- Download and save PEM file. Change the files permissions on your machine with chmod 400

- Launch instance

4)
- add export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH to your .zshrc file

5)
- ssh into the ubuntu server using the pem file and ubuntu server IP address.
Example $ ssh -i /Users/computer/pathto/yourPEMfile.pem ubuntu@12.123.123.123

6)
- sudo apt-get update -y
- sudo apt-get install -y libstdc++6 python-setuptools
- sudo apt-get install -y libgconf-2-4

- pip install --upgrade pip

- source activate tensorflow_p36
- pip install -U turicreate
- jupyter notebook --no-browser

- open another terminal window and make a link with -L from Jupyter notebook port number to localhost port number
	Example $ ssh -i /path to your PEM file/thefilename.pem -L 1234:localhost:4567 ubuntu@ip.address.path.amazonaws.com

- Get Jupiter notebook URL with token from the "$ jupyter notebook --no-browser" command, adjust the port numbers accordingly
	Example output
	"copy and paste one of these URLs:
        http://localhost:1234/?token=56789012345678901234567890abcdefg1234567890
     	or http://127.0.0.1:1234/?token=56789012345678901234567890abcdefg1234567890"

- upload images for training to the ubuntu server

7)
After setting up the environment I can run the turi create code in the jupyter notebook using the CPU

	import turicreate as tc
	style = tc.load_images('/home/ubuntu/tcstyle/')
	content = tc.load_images('/home/ubuntu/tcimg/')
	model = tc.style_transfer.create(style, content, max_iterations=50)
	model.save('/home/ubuntu/tcsave/')

Turi Create runs fine and completes with no errors, but it is slow because it uses the CPU.

If I try to follow the instructions to remove tensorflow and install tensorflow-GPU

(tensorflow_p36) pip uninstall -y tensorflow
(tensorflow_p36) pip install tensorflow-gpu

I get an error while running the code in Jupyter notebook. "cuDNN failed to initialize" error is pasted below. I have checked to make sure CUDA and cuDNN are on the server. AWS also explicitly says it is installed.

I've tried other tensorflow versions. If I try to switch back to using tensor flow with version 1.15.0 I get this error during "pip install tensorflow==1.15.0"

- ERROR: turicreate 6.2.1 has requirement tensorflow<=2.0.1,>=2.0.0, but you'll have tensorflow 1.15.0 which is incompatible.

If I try to switch back to "pip install tensorflow==2.0.1" I get this error during installation

- ERROR: tensorflow-serving-api 1.15.0 has requirement tensorflow~=1.15.0, but you'll have tensorflow 2.0.1 which is incompatible.

In either case I still am unable to run the code on Jupiter notebook using a GPU. I know it can be done as I was able to run the code on a GPU last year around October 2019. Any advice is appreciated.

Jupyter notebook Error...

Using 'image' in style_dataset as feature column and using 'image' in content_dataset as feature column
Using a GPU to create model.
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/turicreate/extensions.py in __run_class_function(self, fnname, args, kwargs)
    289         try:
--> 290             ret = self._tkclass.call_function(fnname, argument_dict)
    291         except RuntimeError as exc:

cy_model.pyx in turicreate._cython.cy_model.UnityModel.call_function()

cy_model.pyx in turicreate._cython.cy_model.UnityModel.call_function()

RuntimeError: An error occurred: UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node Conv2D_26 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/turicreate/toolkits/style_transfer/_tf_model_architecture.py:337) ]]
	 [[mul_23/_217]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node Conv2D_26 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/turicreate/toolkits/style_transfer/_tf_model_architecture.py:337) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node Conv2D_26:
 vgg_block_1_conv_1_weight/read (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/turicreate/toolkits/style_transfer/_tf_model_architecture.py:46)	
 concat_1 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/turicreate/toolkits/style_transfer/_tf_model_architecture.py:434)

Input Source operations connected to node Conv2D_26:
 vgg_block_1_conv_1_weight/read (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/turicreate/toolkits/style_transfer/_tf_model_architecture.py:46)	
 concat_1 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/turicreate/toolkits/style_transfer/_tf_model_architecture.py:434)

**Comment by TobyRoseman** [comment]
With the release of TuriCreate 6.0, we have switched from MXNet to TensorFlow. Currently TuriCreate on Linux only works with TensorFlow 2.0.0 and 2.0.1 (#3003).

This sounds like a cuDNN/CUDA and TensorFlow version mismatch. Certain versions of TensorFlow [expect certain version of cuDNN and CUDA](https://www.tensorflow.org/install/source#gpu). Please make sure that you have cuDNN 7.4 and CUDA 10.0

**Comment by robertallenmartin** [comment]
Thanks Toby. I believe this is the problem as well. My perspective is from a front end developer point of view. Setting up environments like this is uncommon but I am usually successful if I have a good direction. With your comments, I went back to TensorFlows documentation and as they suggest I used Docker instead to build the environment. Again, I can create Turi Create models on the CPU with no problem using these docker images below, but unfortunately still no GPU. 

docker run --gpus all nvidia/cuda:10.0-base nvidia-smi

docker run --gpus all -it --rm --name thedockername tensorflow/tensorflow:2.0.0-gpu-py3-jupyter bash

I feel like I am missing some configuration step with the connection between CUDA and Tensorflow. Tensorflow documentation makes it seem like I only need to run their Docker image for all to work. The docker code above lets me run Turi Create but it still only trains with the CPU. 

The only thing left I can see from the Tensorflow GPU documentation is there are some vague instructions about using Bazel. Do you know if this is what I am missing? Im looking now to see how you install this in a docker container. The documentation isn't very clear to me.

At the end of the day, if there is an easier way is to create an environment for Turi Create Style Transfer I am open to any suggestions. I'm using AWS and Linux because I happen to know it better, and as far as I know the style transfer can't be trained on my Mac GPU. But if there is a more simple way to use a GPU in the cloud, my end goal is only to do the training fast and export a coreML model. Thanks again for your comments.

This is what my AWS linux system seems to have now with the docker build. It doesn't seem to match versions exactly but its what the tensorflow docker image created.  

Python 3.7.7

GCC compiler 
7.5.0

cuDNN
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 5
#define CUDNN_PATCHLEVEL 1

Cuda compilation tools, release 10.0, V10.0.130
NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2

**Comment by TobyRoseman** [comment]
Creating a Style Transfer model should use GPU with macOS 10.14 or higher. That's probably the simplest approach.

Regard the Linux route - I don't think Bazel is the issue. It looks like you have CUDA 10.2 and cuDNN 7.5. However you need cuDNN 7.4 and CUDA 10.0. 

If you have TensorFlow `2.0.0` or `2.0.1` installed, then the following code should tell you if TuriCreate will use the GPU:
```python
import tensorflow as tf
print(tf.test.is_gpu_available())
```

**Comment by anirudhbandi96** [comment]
I faced a similar issue. I saw the same "**cuDNN failed to initialize**" in Jupyter and the following message in my terminal "**tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.5.1 but source was compiled with: 7.6.4.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration."**. 

  I just downloaded the cuDNN version 7.6.5 https://developer.nvidia.com/compute/machine-learning/cudnn/secure/7.6.5.32/Production/10.0_20191031/cudnn-10.0-linux-x64-v7.6.5.32.tgz and followed the installation instructions here https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#installlinux-tar.  This solved my issue but I don't see much improvement in speed here even though it says **"Using a GPU to create model."**

**Comment by robertallenmartin** [comment]
Same here @anirudhbandi96  

https://www.tensorflow.org/install/source suggests the following for GPU as did Toby in the comments above.

Version tensorflow-2.0.0, Python version 2.7, 3.3-3.7, Compiler GCC 7.3.1, cuDNN 7.4, and CUDA 10.0

I have tried using tensorflow-gpu==2.0 and tensorflow==2.0

My cuDNN is definitely 7.4

ubuntu@:~$ cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 1

ubuntu@:~$  cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 1

My CUDA version is 10.0
ubuntu@:~$ cat /usr/local/cuda/version.txt
CUDA Version 10.0.130

However my gcc version 7.5.0. Hopefully that is not the issue. I either get TuriCreate to run on the CPU with tensorflow==2.0 or if I switch to tensorflow-gpu==2.0 I get the same error you get. 

This is the error I get from Jupyter notebook. 

E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.1 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.

This seems to say to me that tensorflow was compiled using 7.6 instead of what it suggests on their site (7.4). Maybe this is the problem.

If i look at nvidia-smi I can see it says CUDA 10.2 but I have updated CUDA using instructions from AWS. https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-base.html and I know the cuda folder has been updated to use 10.0. But maybe this is possibly the problem. 

ubuntu@:~$ cat /usr/local/cuda/version.txt
CUDA Version 10.0.130

ubuntu@:~$ nvidia-smi
Sun May 17 10:41:53 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   29C    P8    14W / 150W |      0MiB /  7618MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

I'd be happy to train on my mac but there are outstanding issues others have reported with style transfer training on AMD GPUs. It trains really fast with my AMD Radeon Pro Vega 20 but as others have suggested, the results are not usable. 

I keep looking at AWS Ubuntu and CUDA to see if I can get it working. If this is the only path. I am eager to get it to train again. I'm not sure what else to try at this point. If anyone understands this error or has been successful at creating a training environment on linux with a GPU maybe they can share their steps or shed some light on what configuration might be missing. Otherwise I'll patiently wait until it works on an AMD GPU. 

I am real excited to see it working again. It's really cool. 



![cat4](https://user-images.githubusercontent.com/4595271/82151984-959e4680-98b2-11ea-8100-b8e76195cf27.gif)

**Comment by robertallenmartin** [comment]
If this helps anyone, I was successful by rolling back to TuriCreate version 5.7.1 which uses MXNet along with renting some powerful GPUs (g3.8xlarge - 2 Tesla M60s) on AWS. 18,000 iterations took around 2.5 hours to train with 32 style images and 458 training images. 

TuriCreate 6.2.2 is easy to install but I think somewhere along the line of configuring a Linux AWS EC2 environment and aligning all the dependency version requirements for a particular TensorFlow version is not clear. 

AWS has documentation on updating the runtime version of CUDA but I imagine the problem I might be having is located with the original installation of the CUDA driver and cuDNN versions by AWS. They are the most recent versions of those libraries and of course incompatible. So even though it appears I am updating the runtime versions, the original driver installation must be causing the problems.

As a front end developer I can respect the complexity of setting up environments. Installing GPU drivers on a machine rented by the hour is simply venturing into territory that it is time consuming and complex. It was easier to roll back to what I previously had working on AWS with MXNet and TuriCreate 5.7.1. TuriCreate is very interesting, I'll be excited when the issues similar to #3190 are resolved. Ultimately TuriCreate 6.2.2 would be cheaper and faster for me since I could train on my Mac Vega 20 and wouldn't need to use AWS or Linux.
