### ISSUE TITLE
loss is nan when using beta to train detector 

### ISSUE THREAD

**Issue by yousifKashef** [apple/turicreate#629]
Hi,
I’m using the beta (turiCreate 5) to train an image detector. The code I’m using to train the detector is the same that I used to train a detector using the last version of Turi Create (which went fine). Now, I’m getting nan in the loss category as it’s training with my mac’s GPU. Is this a bug or should I adjust my code to fix this?
Thanks!

**Comment by srikris** [comment]
@yousifKashef: Can you tell us which GPU you have. We have seen some select GPUs where we get a nan loss and are trying to track it down and fix it soon.

For now you can do:

```
import turicreate
turicreate.config.set_num_gpus(0)
```

This is an important bug and its high on our list.

**Comment by yousifKashef** [comment]
Hi Srikris,
I have an imac 5k (late 2015) with an AMD Radeon R9 M395 graphics processor with 2 GB of dedicated GDDR5 memory. I’ll Post the log from terminal later today. 
Thanks

**Comment by TobyRoseman** [comment]
Hi @yousifKashef - If you can post the logs you mentioned, that would be helpful.

It would also be helpful if you can share the code too. In particular I would like to know the value getting used for the `model` parameter in `image_classifier.create(...)`. Are you using `VisionFeaturePrint_Screen`?

**Comment by yousifKashef** [comment]
Yousifs-iMac:training yousif$ python train.py
Downloading https://docs-assets.developer.apple.com/turicreate/models/darknet.params
Download completed: /var/folders/3y/ykbsfsg52n91gbvh45m00zlc0000gn/T/model_cache/darknet.params
Using GPU to create model (AMD Radeon R9 M380)
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 4.287        | 30.0         |
| 5            | nan          | 50.3         |
| 9            | nan          | 61.9         |
| 12           | nan          | 74.3         |
| 15           | nan          | 86.4         |
| 20           | nan          | 101.2        |
| 25           | nan          | 116.7        |
| 31           | nan          | 133.0        |
| 36           | nan          | 150.8        |
| 41           | nan          | 166.8        |
| 46           | nan          | 184.5        |
| 51           | nan          | 202.4        |
| 57           | nan          | 220.5        |
| 61           | nan          | 230.6        |
| 63           | nan          | 254.2        |
| 67           | nan          | 267.7        |
| 72           | nan          | 284.4        |
| 77           | nan          | 302.0        |
| 81           | nan          | 312.2        |
| 84           | nan          | 324.8        |
| 88           | nan          | 339.0        |
| 93           | nan          | 355.5        |
| 97           | nan          | 365.9        |
| 99           | nan          | 376.6        |
| 103          | nan          | 391.8        |
| 108          | nan          | 411.7        |
| 112          | nan          | 423.4        |
| 114          | nan          | 434.7        |
| 118          | nan          | 444.8        |
| 120          | nan          | 455.1        |
| 124          | nan          | 468.4        |
| 129          | nan          | 485.6        |
| 134          | nan          | 500.6        |
| 140          | nan          | 516.9        |

**Comment by yousifKashef** [comment]
import turicreate as tc

modelName = 'output'

# Load the data
data = tc.SFrame('training.sframe')

# Make a train-test split
train_data, test_data = data.random_split(0.8)

# Automatically picks the right model based on your data.
model = tc.object_detector.create(train_data, feature='image', annotations='annotations', max_iterations=10000)

# Save the model for later use in Turi Create
# Important to save in case something after breaks the script
model.save(modelName + '.model')

# Mean average Precision
scores = model.evaluate(data)
print(scores['mean_average_precision'])

# Export for use in CoreML
model.export_coreml(modelName.title() + 'Classifier.mlmodel')

**Comment by nickjong** [comment]
Okay, we've figured out that this problem is ultimately due to running out of memory on the GPU. A smaller batch size resolves the issue. We should make the batch size scale automatically according to available memory, but in the meantime you should be able to get things going by changing your invocation to something like:
```
model = tc.object_detector.create(train_data, feature='image', annotations='annotations', _advanced_parameters={'batch_size' : 16})
```
Note that if you specify the number of iterations explicitly, you'll need to double that number to achieve the same number of passes through the training data. (The current default batch size is 32.)

**Comment by silvywilson** [comment]
I am also seeing the same 'NaN' for loss after the first iteration while using GPU.  When changing to CPU it runs correctly.  The OS version is 10.14 (Mojave).  GPU is AMD Radeon 455  (2048 MB).  Batch size is 16.  I tried changing the batch size to 8, but it did not take it.  The Mac is a MacBook Pro with 16GB RAM. 
 Does this mean I cannot use GPU to train?

**Comment by nickjong** [comment]
@silvywilson Sigh, I suspect this is the same issue as #1236, which is resolved in macOS 10.14.4. Let me know if you encounter this issue after upgrading to that version (currently still in public beta).

**Comment by chompysticks** [comment]
I have the same problem “batch_size doesn’t stick” even after updating to 10.14.4 beta 3. 

I’m using object detector with image sizes of 1024x1024 (same objects I’m attempting to detect are small). My GPU is Radeon 490

**Comment by nickjong** [comment]
@chompysticks Hmm, what do you mean "batch_size doesn't stick"? Could you copy how you're invoking `tc.object_detector.create` and what the initial output is?

**Comment by dmcgloin** [comment]
Seeing same issue running macOS 10.14.4 Beta (18E215a).

After adding `_advanced_parameters={'batch_size' : 8}`...

I got this error:

```Traceback (most recent call last):
  File "Train.py", line 25, in <module>
    model = tc.object_detector.create(train_data, feature='image', annotations='annotations', _advanced_parameters={'batch_size' : 8}) #, max_iterations=5)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 264, in create
    raise _ToolkitError('Unknown advanced parameters: {}'.format(unsupported))
turicreate.toolkits._main.ToolkitError: Unknown advanced parameters: {'batch_size'}```

**Comment by vhicks** [comment]
@dmcgloin add it as a regular parameter and not an object, that got rid of the error for me.

`model = tc.object_detector.create(train_data, feature='image', annotations='annotations', batch_size=16)`

**Comment by nickjong** [comment]
Ah, yes, since my comment last June, `batch_size` got promoted to a real (documented) parameter

**Comment by dmcgloin** [comment]
Thanks @vhicks and @nickjong. I corrected to use `batch_size` real parameter, but it seems to ignore value of `8`. Anyway, still getting `Loss` as `NAN` for second iteration onward.

**Comment by nickjong** [comment]
@dmcgloin What version of Turi Create are you running? And what output do you get in response to your `turicreate.object_detector.create` call?

**Comment by jamois** [comment]
Just noticed for the first time the `nan` issue when I enabled GPU.  Read the notes above and made the batch size change and it worked and did not work.  Here is my line of code:
`newModel = tc.object_detector.create(test_data, feature='image', annotations='annotation', \
                            max_iterations=iterations, model="darknet-yolo", batch_size=16)`
Strangely, the first time I run it with GPU enabled and batch_size=16 added to the parameters, it fails with the following error:
`Traceback (most recent call last):
 File "turiObjects.py", line 277, in <module>
   output = turiObjects(imagefolder, gtfolder, modelname, iterations, fixorient)
 File "turiObjects.py", line 206, in __init__
   max_iterations=iterations, model="darknet-yolo", batch_size=16)
 File "/Users/jamey/Library/Python/2.7/lib/python/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 349, in create
   iterations=num_iterations)
 File "/Users/jamey/Library/Python/2.7/lib/python/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 295, in __init__
   "The following row(s) did not conform to this format:" + s)
turicreate.toolkits._main.ToolkitError: Invalid object annotations discovered.

A valid annotation is a dictionary that defines 'label' and 'coordinates',
the latter being a dictionary that defines 'x', 'y', 'width', and 'height'.
The following row(s) did not conform to this format:`

For some reason, I decided to simply run it again (I know, makes no sense) and it worked.  I'm not sure this is related to enabling GPU but wanted to add my comment just in case.

Turi version: 5.4
macOS: 10.14.4
Machines: MacBook Pro (Radeon Pro 460 4GB) and iMac (AMD Radeon R9 M395 2GB)
